/*
 Network Stack for PSoC3-ENC28J60 hardware
 -----------------------------------------
 Title  : Webserver functions.
 Author : Kartik Mankad
 Date : 30-06-12
 This code is licensed as CC-BY-SA 3.0
 Description : Webserver functionality that allows the PSoC to serve dynamic text/html webpages.
*/

#include "IPStackMain.h"
#include <string.h>
#include <stdio.h>

int WebServer_ProcessRequest(TCPhdr *tcp)
{
	unsigned int datalen;
	unsigned int temp;
	unsigned char templine[40];

	if (strncmp("GET ", (unsigned char *)tcp + sizeof(TCPhdr), 4) != 0) {
		//Reply with a 200 OK with queries that arent of type GET.
		//
		// for possible HTTP Status codes(404,301 etc) see:
		// http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
		datalen = AddWebServerData(tcp, 0, "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\n\r\n");
	}

	DieTemp_GetTemp((int16*)&temp);
	sprintf(templine,"<h2>PSoC Temperature is %d deg C</h2>",temp);

	if (strncmp("/ ", (unsigned char *)tcp + sizeof(TCPhdr) + 4, 2) == 0) {
		datalen = AddWebServerData(tcp, 0, "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\n\r\n");
		datalen = AddWebServerData(tcp, datalen, "<title>ENC28J60-PSoC3</title>");
		datalen = AddWebServerData(tcp, datalen, "<h1>ENC28J60-PSoC3</h1>");
		datalen = AddWebServerData(tcp, datalen, "<hr>");
		datalen = AddWebServerData(tcp, datalen, templine);
	}

	return ReplyTCP_Webserver(tcp, datalen);
}

/*******************************************************************************
* Function Name: AddWebServerData
********************************************************************************
* Summary:
*   This function is used to append webpage data to the outgoing reply
*   to the GET query.
*
* Parameters:
*    tcp - pointer to a TCP packet that has the GET Query.
*    pos  - position in the data part where data must be appended.
*    str - the constant string that is to be appened.This is usually the HTML.
* Returns:
*   current position of data in the TCP packet.
*******************************************************************************/
int AddWebServerData(TCPhdr* tcp, unsigned int pos, const char* str)
{
	while (*str) {
		*((unsigned char *)tcp + sizeof(TCPhdr) + pos) = *str;
		pos++;
		str++;
	};

	return pos;
}

/*******************************************************************************
* Function Name: ReplyTCP_Webserver
********************************************************************************
* Summary:
*   This is used to send the webpage generated by AddWebServerData,in response
*   to the GET query.This function ACK's the GET query,and then sends the reply.
*
* Parameters:
*    tcp - pointer to a TCP packet that has the Webpage.
*    len  - length of this packet.
* Returns:
*   TRUE(0)- if the packet was successfully sent.
*   FALSE(1) - if the packet was not successful in transmission.
*******************************************************************************/
int ReplyTCP_Webserver(TCPhdr *tcp, unsigned int datlen)
{
	/*Send an ACK for the GET query*/
	ackTcp(tcp, ntohs(tcp->ip.len) + 14, TF_NONE);

	/* Based on that ACK we sent, create the reply to the GET query */
	tcp->ACK = 1;
	tcp->PSH = 1;
	tcp->FIN = 1;

	/* Set the length field */
	tcp->ip.len = htons(sizeof(TCPhdr) + datlen - sizeof(EtherNetII));

	tcp->ip.chksum = 0;
	tcp->ip.chksum = htons(checksum((unsigned char *)tcp + sizeof(EtherNetII), sizeof(IPhdr) - sizeof(EtherNetII), 0));

	tcp->chksum = 0;
	tcp->chksum = htons(checksum((unsigned char *)tcp->ip.source, 0x08 + 0x14 + datlen, 2));

	return tx_packet(tcp, sizeof(TCPhdr) + datlen);
 }

/* [] END OF FILE */
