/*
 Network Stack for PSoC3-ENC28J60 hardware
 -----------------------------------------
 Title  : Webserver functions.
 Author : Kartik Mankad
 Date : 30-06-12
 This code is licensed as CC-BY-SA 3.0
 Description : Webserver functionality that allows the PSoC to serve dynamic text/html webpages.
*/
#ifndef WEBSERVER_H
#define WEBSERVER_H


/*******************************************************************************
* Function Name: WebServer_ProcessRequest
********************************************************************************
* Summary:
*   **This function should be modified to
*   implement web url parsing and web page generation based on that.**
*   This function parses the GET query,and generates the relevant Webpage,
*   and sends it to the client.It closes the connection by ACKing the FINACK.
*
*   This function must be called immediately after WebServer_SetupConnection.
*
* Parameters:
*   TCPPackData - pointer to a TCP packet that has the GET Query.
*
* Returns:
*   TRUE(0)- if the webpage was successfully sent.
*   FALSE(1) - if the webpage was not successful in transmission.
*******************************************************************************/
int WebServer_ProcessRequest(TCPhdr *tcp);

/*******************************************************************************
* Function Name: AddWebServerData
********************************************************************************
* Summary:
*   This function is used to append webpage data to the outgoing reply
*   to the GET query.
*
* Parameters:
*    TCPPkt - pointer to a TCP packet that has the GET Query.
*    pos  - position in the data part where data must be appended.
*    str - the constant string that is to be appened.This is usually the HTML.
* Returns:
*   current position of data in the TCP packet.
*******************************************************************************/
int AddWebServerData(TCPhdr *tcp, unsigned int pos, const char *str);

/*******************************************************************************
* Function Name: ReplyTCP_Webserver
********************************************************************************
* Summary:
*   This is used to send the webpage generated by AddWebServerData,in response
*   to the GET query.This function ACK's the GET query,and then sends the reply.
*
* Parameters:
*    TCPPkt - pointer to a TCP packet that has the Webpage.
*    len  - length of this packet.
* Returns:
*   TRUE(0)- if the packet was successfully sent.
*   FALSE(1) - if the packet was not successful in transmission.
*******************************************************************************/
int ReplyTCP_Webserver(TCPhdr *tcp, unsigned int len);

#endif

/* [] END OF FILE */
